spring:
  cache:
    type: redis
    cache-names: product-cache
#    redis:
 #     time-to-live: 5000
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.cache: TRACE
server:
  port: 8081
